[2022-07-03 13:42:08,783] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task manual__2022-07-03T13:42:04.897144+00:00 [queued]>
[2022-07-03 13:42:08,839] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v2.second_task manual__2022-07-03T13:42:04.897144+00:00 [queued]>
[2022-07-03 13:42:08,846] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-03 13:42:08,859] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-07-03 13:42:08,863] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-03 13:42:08,943] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): second_task> on 2022-07-03 13:42:04.897144+00:00
[2022-07-03 13:42:08,981] {standard_task_runner.py:52} INFO - Started process 1249 to run task
[2022-07-03 13:42:09,007] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'second_task', 'manual__2022-07-03T13:42:04.897144+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmphedyiuwi', '--error-file', '/tmp/tmpxfeg5ujj']
[2022-07-03 13:42:09,014] {standard_task_runner.py:80} INFO - Job 5: Subtask second_task
[2022-07-03 13:42:09,332] {task_command.py:370} INFO - Running <TaskInstance: our_first_dag_v2.second_task manual__2022-07-03T13:42:04.897144+00:00 [running]> on host 677d749653ef
[2022-07-03 13:42:09,924] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v2
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-03T13:42:04.897144+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-03T13:42:04.897144+00:00
[2022-07-03 13:42:09,959] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-03 13:42:09,967] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am the second task running after task1']
[2022-07-03 13:42:10,016] {subprocess.py:85} INFO - Output:
[2022-07-03 13:42:10,031] {subprocess.py:92} INFO - hey, I am the second task running after task1
[2022-07-03 13:42:10,045] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-03 13:42:10,165] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, execution_date=20220703T134204, start_date=20220703T134208, end_date=20220703T134210
[2022-07-03 13:42:10,254] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-03 13:42:10,370] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
